name: Build and upload wrapper
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Building
    steps:

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Create work directory
        run: mkdir work

      - name: Create bin directory
        run: mkdir bin

      - name: Build
        run: |
          miner_name="tnn-miner"
          version="v0.4.0.a2.2.1"
          
          hiveos_asset_name="${miner_name}-${version}_hiveos"
          hiveos_archive="bin/${hiveos_asset_name}.tar.gz"
          cp -r ./hive-os ./work/${miner_name}
          sed 's/^name="minername"/name="${miner_name}"/g' -i ./work/${miner_name}/h-manifest.conf
          sed 's/^ver="custom"/ver="${version}"/g' -i ./work/${miner_name}/h-stats.sh
          chmod +x ./work/${miner_name}/h-run.sh
          chmod +x ./work/${miner_name}/h-stats.sh
          chmod +x ./work/${miner_name}/${miner_name}
          tar -czvf "${hiveos_archive}" -C ./work ${miner_name}
          rm -r ./work/*

          mmpos_asset_name="${miner_name}-${version}_mmpos"
          mmpos_archive="bin/${mmpos_asset_name}.tar.gz"
          cp -r ./mmpos ./work/${miner_name}
          sed 's/^name="minername"/name="${miner_name}"/g' -i ./work/${miner_name}/mmp-external.conf
          sed 's/^ver="custom"/ver="${version}"/g' -i ./work/${miner_name}/mmp-external.conf
          chmod +x ./work/${miner_name}/mmp-stats.sh
          chmod +x ./work/${miner_name}/${miner_name}
          tar -czvf "${mmpos_archive}" -C ./work ${miner_name}
          

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        
        with:
          files: |
            bin/*.tar.gz
          tag_name: "tnn-miner-0.4.0"
          token: ${{ secrets.token }}
